name: Run tests and upload coverage

on: 
  push:
    branches:
      - main  # Specify your main branch here

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npx jest --coverage --coverageReporters=cobertura

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/cobertura-coverage.xml  # Adjust the path if necessary
